ASR/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from .views import (
    settings, notifications_settings, sign_in, sign_up, profile, telega_book, 
    telega_fetch, check_schedule, book, telega_auth, telega_fetch_rooms
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('social-auth/', include('social_django.urls', namespace="social")),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('notifications_settings', notifications_settings,
         name='notifications_settings'),
    path('profile', profile, name='profile'),
    path('settings', settings, name='settings'),
    path('sign_in', sign_in, name='sign_in'),
    path('sign_up', sign_up, name='sign_up'),
    path('MainApp/', include('MainApp.urls')),
    
    path('ajax/check_schedule', check_schedule, name='check_schedule'),
    path('ajax/book', book, name='book'),

    path('telega/auth',telega_auth),
    path('telega/book', telega_book),
    path('telega/fetch', telega_fetch),
    path('telega/fetch/rooms', telega_fetch_rooms),
]

MainApp/urls.py
from django.urls import path, re_path
from .views import *

app_name = 'MainApp'
urlpatterns = [
    path('index', index, name='index'),
    re_path(r'change_room/(?P<show>\D+)', change_room, name='change_room'),
    # path('change_seat/<str:place>/<int:place_id>', change_seat, name='change_seat'),
    # path('change_time/<str:place>/<int:place_id>', change_time, name='change_time'),
    path('my_booking', my_booking, name='my_booking'),
]

ASR/views.py
from json import dumps
from django.shortcuts import render
from django.http import HttpResponseRedirect, JsonResponse
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
# from django.contrib import messages
# from django.urls import reverse
from MainApp.models import Workplace_Schedule, Meeting_Room_Schedule, User, User_preferences, Meeting_Room, Workplace
from datetime import datetime, timezone, timedelta
from filler import check_place_schedule, place_shedule_strings, place_strings
from yandex_cal import send_event
from social_django.models import UserSocialAuth


@login_required()
def settings(request):
    return render(request, 'settings.html')


@login_required()
def profile(request):
    if request.is_ajax and request.method == "POST" and request.POST.get('ntz', ''):
        timezones = [
            'Europe/Kaliningrad, UTC+02:00',
            'Europe/Moscow, UTC+03:00',
            'Europe/Volgograd, UTC+04:00',
            'Asia/Yekaterinburg, UTC+05:0s0',
            'Asia/Omsk, UTC+06:00',
            'Asia/Krasnoyarsk, UTC+07:00',
            'Asia/Irkutsk, UTC+08:00',
            'Asia/Yakutsk, UTC+09:00',
            'Asia/Vladivostok, UTC+10:00',
            'Asia/Sakhalin, UTC+11:00',
            'Asia/Kamchatka, UTC+12:00'
        ]
        new_timezone = request.POST.get('ntz', '')
        if new_timezone not in timezones:
            return JsonResponse({"error": "Invalid timezone"}, status=400)
        ups = request.user.user_preferences
        ups.timezone = new_timezone
        ups.save()
        return JsonResponse(dumps(f'timezone changed to {new_timezone}'), safe=False, status=200)
    
    if request.is_ajax and request.method == "POST" and request.POST.get('app_pass', ''):
        app_pass = request.POST.get('app_pass', '')
        ups = request.user.user_preferences
        ups.app_password = app_pass
        ups.save()
        return JsonResponse(dumps(f'app password changed to {app_pass}'), safe=False, status=200)

    try:
        timezone = request.user.user_preferences.timezone
        app_password = request.user.user_preferences.app_password
    except Exception:
        ups = User_preferences.objects.create(
            user=request.user, timezone='Asia/Yekaterinburg, UTC+05:00')
        timezone = ups.timezone
        app_password = ''
    return render(request, "profile.html", {"timezone": timezone, "app_password": app_password})


@login_required()
def notifications_settings(request):
    return render(request, 'notifications_settings.html')


@login_required()
def sign_in(request):
    return render(request, 'sign_in.html')


@login_required()
def sign_up(request):
    return render(request, 'sign_up.html')


def check_schedule(request):
    if request.method == 'GET':
        date = request.GET.get('date', '')
        start = request.GET.get('start', '')
        finish = request.GET.get('finish', '')
        place_id = request.GET.get('place_id', '')
        place_type = request.GET.get('place_type', '')
        username = request.GET.get('username', request.user.username)
        repeat = request.GET.get('repeat', '')
        # include_holydays = request.GET.get('include_holydays', '') later

        if not all([date, start, finish, place_id, place_type, username, repeat]):
            return JsonResponse(dumps({"Some data is missing":
                                       [date, start, finish, place_id, place_type, username, repeat]}), safe=False, status=400)

        user = User.objects.filter(username=username)[0]
        dates = []
        if repeat == 'current_week' or repeat == 'next_and_current_week':
            dates = [(datetime.strptime(date, '%d/%m/%y').date() + timedelta(days=x)).strftime('%d/%m/%y')
                     for x in range(5 - datetime.strptime(date, '%d/%m/%y').weekday())]
        if repeat == 'next_and_current_week':
            dates.extend(
                [(datetime.strptime(dates[-1], '%d/%m/%y') + timedelta(days=x)).strftime('%d/%m/%y') for x in range(3, 8)])
        if repeat == 'once':
            dates = [date]
        str_utcoffset = user.user_preferences.timezone.split(',')[-1].strip()
        # user_tz = user.user_preferences.timezone.split(',')[0].strip()

        responses = {}
        fails = 0
        for date in dates:
            dt_start = datetime.strptime(date + ' ' + start, '%d/%m/%y %H:%M')
            dt_finish = datetime.strptime(
                date + ' ' + finish, '%d/%m/%y %H:%M')
            res, cause = check_place_schedule(
                place_id, str_utcoffset, dt_start, dt_finish, place_type)
            responses[date] = f'{cause}'
            if not res:
                fails += 1
        
        if len(responses) == fails:
            return JsonResponse(dumps({'fail': 'All booked'}), safe=False, status=200)

        return JsonResponse(dumps(responses), safe=False, status=200)


def book(request):
    if request.is_ajax and request.method == "POST":
        # get the form data
        date = request.POST.get('date', '')
        start = request.POST.get('start', '')
        finish = request.POST.get('finish', '')
        place_id = request.POST.get('place_id', '')
        place_type = request.POST.get('place_type', '')
        username = request.POST.get('username', request.user.username)
        repeat = request.POST.get('repeat', '')

        if not all([date, start, finish, place_id, place_type, username, repeat]):
            return JsonResponse(dumps({"Some data is missing":
                                       [date, start, finish, place_id, place_type, username, repeat]}), safe=False, status=400)

        user = User.objects.filter(username=username)[0]
        try:
            str_utcoffset = user.user_preferences.timezone.split(
                ',')[-1].strip()
        except Exception:
            return JsonResponse(dumps({'error': 'User has no timezone'}), safe=False, status=400)

        dates = []
        if repeat == 'current_week' or repeat == 'next_and_current_week':
            dates = [(datetime.strptime(date, '%d/%m/%y').date() + timedelta(days=x)).strftime('%d/%m/%y')
                     for x in range(5 - datetime.strptime(date, '%d/%m/%y').weekday())]
        if repeat == 'next_and_current_week':
            dates.extend(
                [(datetime.strptime(dates[-1], '%d/%m/%y') + timedelta(days=x)).strftime('%d/%m/%y') for x in range(3, 8)])
        if repeat == 'once':
            dates = [date]

        responses = {}
        for date in dates:
            dt_start = datetime.strptime(date + ' ' + start, '%d/%m/%y %H:%M')
            dt_finish = datetime.strptime(date + ' ' + finish, '%d/%m/%y %H:%M')

            res, cause = check_place_schedule(
                place_id, str_utcoffset, dt_start, dt_finish, place_type)
            responses[date] = {'fail': cause}
            if res:
                if place_type == 'Workplace':
                    Workplace_Schedule.objects.create(workplace_id=place_id, user_id=user.id, start=dt_start.astimezone(
                        timezone.utc), finish=dt_finish.astimezone(timezone.utc))
                    responses[date] = {'from': dt_start.strftime("%H:%M"), 'to': dt_finish.strftime("%H:%M")}
                    send_event(f'Workplace #{place_id}', dt_start, dt_finish, user.email, user.user_preferences.app_password)

                elif place_type == 'Room':
                    Meeting_Room_Schedule.objects.create(meeting_room_id=place_id, user_id=user.id, start=dt_start.astimezone(
                        timezone.utc), finish=dt_finish.astimezone(timezone.utc))
                    responses[date] = {'from': dt_start.strftime("%H:%M"), 'to': dt_finish.strftime("%H:%M")}
                    send_event(f'Room #{place_id}', dt_start, dt_finish, user.email, user.user_preferences.app_password)
        
        return JsonResponse(dumps(responses), safe=False, status=200)

    # some error occured
    return JsonResponse({"error": "unknown error"}, status=400)


@csrf_exempt
def telega_book(request):
    if request.method == "POST":
        # get the request data
        date = request.POST.get('date', '')
        start = request.POST.get('start', '')
        finish = request.POST.get('finish', '')
        place_id = request.POST.get('place_id', '')
        place_type = request.POST.get('place_type', '')
        username = request.POST.get('username', '')

        if not all([date, start, finish, place_id, place_type, username]):
            # return JsonResponse(dumps([x for x in request.POST.items()]), safe=False, status=400)
            return JsonResponse(dumps({"Some data is missing": [date, start, finish, place_id, place_type, username]}),
                                safe=False, status=400)

        dt_start = datetime.strptime(date + ' ' + start, '%d/%m/%y %H:%M')
        dt_finish = datetime.strptime(date + ' ' + finish, '%d/%m/%y %H:%M')
        # str_utcoffset = 'UTC' + start.split(' ')[-1]
        user = User.objects.filter(username=username)[0]
        str_utcoffset = user.user_preferences.timezone.split(',')[-1].strip()
        user_tz = user.user_preferences.timezone.split(',')[0].strip()

        res, cause = check_place_schedule(
            place_id, str_utcoffset, dt_start, dt_finish, place_type)
        if not res:
            return JsonResponse(dumps({"error": cause}), safe=False, status=400)

        if place_type == 'Workplace':
            Workplace_Schedule.objects.create(workplace_id=place_id, user_id=user.id,
                                              start=dt_start.astimezone(
                                                  timezone.utc),
                                              finish=dt_finish.astimezone(timezone.utc))
            # response = {'start': start, 'finish': finish, 'date': date}
            response = f'booked on {date} from {start} to {finish}, {user_tz}'

ASR/templates/footer.html
{% load static %}
<!--<footer class="container" id="footer">-->
<!--  <p>© 2020 G&3B. · <a href="#">Privacy</a> · <a href="#">Terms</a></p>-->
<!--</footer>-->


<!--    <script>window.jQuery || document.write('<script src="/docs/4.5/assets/js/vendor/jquery.slim.min.js"><\/script>')</script>-->
<!--<script src="/docs/4.5/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>-->

<!--<app-content ng-version="10.1.5"></app-content><div at-magnifier-wrapper=""><div class="at-theme-light"><div class="at-base notranslate" translate="no"><div class="Z1-AJ" style="top: 0px; left: 0px;"></div></div></div></div></body>-->
<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
<script src="{% static 'js/jquery-ui.min.js' %}"></script>
<script src="{% static 'js/jquery-ui-timepicker-addon.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
<script src="https://kit.fontawesome.com/716a81b06b.js" crossorigin="anonymous"></script>
</body>
</html>

ASR/templates/header.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>
    {% block title %}
    ASR
    {% endblock %}
  </title>
  <link rel="shortcut icon" href="{% static 'images/aventicab.png'%}" type="image/png">
  <link rel="apple-touch-icon" href="{% static 'images/aventicab.png'%}" type="image/png">
  <link rel="icon" href="{% static 'images/aventicab.png'%}" type="image/png">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
    integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="/static/css/style.css">
  <link rel="stylesheet" href="{% static 'css/jquery-ui.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/jquery-ui-timepicker-addon.css' %}">
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark  sticky-top bg-dark ">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample08"
      aria-controls="navbarsExample08" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-md-center" id="navbarsExample08">
      <ul class="navbar-nav">
        {% if request.user.is_authenticated and not request.user.user_preferences.timezone %}

        <li class="nav-item">
          <button class="btn btn-danger btn-sm" type="button">
            <a class="nav-link" href="{% url 'profile' %}">
              Часовой пояс не выбран!
            <span class="nav-link"></span></a>
          </button>
        </li>
        {% endif %}

        <li nav-item>
          <a href="https://vk.com/away.php?to=http%3A%2F%2Ft.me%2Fasrpro_bot&el=snippet"> <img src="https://pbs.twimg.com/media/Eazot-lXYAAnyHh.png" width="32"> </a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'MainApp:index' %}">ASR <span class="sr-only">(current)</span></a>
        </li>
        
        <li class="nav-item dropdown"  >
          <a class=" nav-link dropdown-toggle"  href="#" id="dropdown_work" data-toggle="dropdown" aria-haspopup="true"
            aria-expanded="false">Забронировать место</a>
          <div class="dropdown-menu" aria-labelledby="dropdown08">
            <a class="dropdown-item" href="{% url 'MainApp:change_room' 'workplaces' %}">Забронировать место</a>
            <a class="dropdown-item" href="{% url 'MainApp:change_room' 'rooms' %}">Забронировать переговорку</a>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link" id="my_work" href="{% url 'MainApp:my_booking' %}">Мои бронирования</a>
        </li>
        
        {% if request.user.is_authenticated %}
        <li class="nav-item dropdown"  >
          <a class="nav-link dropdown-toggle"  href="#" id="dropdown08" data-toggle="dropdown" aria-haspopup="true"
            aria-expanded="false">Профиль</a>
          <div class="dropdown-menu" aria-labelledby="dropdown08">
            <a class="dropdown-item" href="{% url 'profile' %}">Мой профиль</a>
            <a class="dropdown-item" href="#">Что-то еще</a>
            <a class="dropdown-item" href="{% url 'logout' %}">Выйти</a>
          </div>
        </li>
        {% else %}
        <li class="nav-item"  >
          <a class="nav-link" id="input_link" href="{% url 'login' %}">Войти</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </nav>



  {% block content %}
  <p>Placeholder text in index template. Replace with page content.</p>
  {% endblock %}
  {% include 'footer.html' %}
  {% block page_scripts %}
  {% endblock %}

ASR/templates/login.html
{% extends "header.html" %}
{% block title %}Login{% endblock title %}
{% block content %}

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
{% if user.is_authenticated %}
<p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
{% else %}
<p>Please login to see this page.</p>
{% endif %}
{% endif %}
<h1></h1>

<div class="container mt-5">

    <div class="row justify-content-center">
        <div class="input-card">
            <h1 class="text-center">Вход</h1>

            <div class="card-body">
                <form method="post" action="{% url 'login' %}">
                    {% csrf_token %}
                    <table class="mb-3">
                        <tr>
                            <td>{{ form.username.label_tag }}</td>
                            <td>{{ form.username }}</td>
                        </tr>
                        <tr>
                            <td>{{ form.password.label_tag }}</td>
                            <td>{{ form.password }}</td>
                        </tr>
                    </table>
                    <input class="btn btn-primary" type="submit" value="Войти">
                    <input type="hidden" name="next" value="{{ next }}">
                    <a href="sign_up.html" class="btn btn-primary">Зарегистрироваться</a>
                </form>


                <div class=" mt-3">
                    <a class="ml-2" type="submit"
                        href="{% url 'social:begin' 'yandex-oauth2' %}">
                        <img class="doc-c-image doc-c-image"
                            src="//yastatic.net/doccenter/images/tech2.yandex.ru/ru/passport/doc/dg/freeze/6rDvXXB38VOBgtxkOExfxnZPUWs.png">
                    Войти через Яндекс</a>
                </div>

            </div>
        </div>
    </div>
    {% endblock %}

ASR/templates/logout.html
{% extends "header.html" %}
{% block title %}Logout{% endblock title %}
{% block content %}
<h1>Logged Out</h1>
{% endblock content %}

ASR/templates/notifications_settings.html
{% extends 'header.html' %}
{% block title %}
  Notifications
{% endblock %}
{% block content %}
	<p>Настройки уведомлений</p>
{% endblock %}

ASR/templates/profile.html
{% extends 'header.html' %}
{% block title %}
Profile
{% endblock %}
{% block content %}

<div class="container m-5">




    <div class="card mb-4 shadow-sm">
        <div class="card-header">
            <h4>{{ request.user.first_name }} {{ request.user.last_name }}</h4>
        </div>

        <div class="card-body">
            <!-- <img src={{request.user.default_avatar_id}} alt=""> -->
            <hr class="featurette-divider">
            <label for="current_timezone">Часовой пояс:</label>
            <h6 class="card-text" id="current_timezone">{{ timezone }}</h6>
            <div class="d-flex justify-content-between align-items-center">
            </div>
        </div>
    </div>

    <li class="list-group-item d-flex justify-content-between lh-condensed shadow-sm mb-4 ">
        <div>
            <h6>Изменить данные:</h6>
            <div class="container">
                <form action="" method="post">
                    <label for="selectTimezone">Часовой пояс</label>
                    <div class="input-group">
                        <select class="custom-select" id="selectTimezone"
                            aria-label="Example select with button addon">
                            <option>Europe/Kaliningrad, UTC+02:00</option>
                            <option>Europe/Moscow, UTC+03:00</option>
                            <option>Europe/Volgograd, UTC+04:00</option>
                            <option>Asia/Yekaterinburg, UTC+05:00</option>
                            <option>Asia/Omsk, UTC+06:00</option>
                            <option>Asia/Krasnoyarsk, UTC+07:00</option>
                            <option>Asia/Irkutsk, UTC+08:00</option>
                            <option>Asia/Yakutsk, UTC+09:00</option>
                            <option>Asia/Vladivostok, UTC+10:00</option>
                            <option>Asia/Sakhalin, UTC+11:00</option>
                            <option>Asia/Kamchatka, UTC+12:00</option>
                        </select>
                        <div class="input-group-append">
                            <button id="changeTimezone" class="btn btn-outline-primary" type="submit">Сохранить</button>
                        </div>
                    </div>
                    {% csrf_token %}
                </form>
            </div>

            <div class="container mt-3">
                <form action="" method="post">
                    <label for="selectPassword">Пароль приложения, для отправки событий в календарь
                        <a href="https://yandex.ru/support/passport/authorization/app-passwords.html">(Как его получить?)</a></label>
                    <div class="input-group">

                     <input type="text" class="form-control" id="appPassword" value="{{ app_password }}">
                        <div class="input-group-append">
                            <button id="changePassword" class="btn btn-outline-primary" type="submit">Сохранить</button>
                        </div>
                    </div>
                    {% csrf_token %}
                </form>
            </div>
        </div>
    </li>

    <a href="{% url 'logout' %}" style="text-decoration: none;">
        <li class="list-group-item d-flex justify-content-between lh-condensed shadow-sm ">

            <div>
                <h6 class="text-danger">Выйти</h6>
                <small class="text-muted"> что-нибудь</small>
            </div>

        </li>
    </a>
    </ul>



</div>
{% endblock %}

{% block page_scripts %}
<script>
    $(function () {
        let ctz = $("#current_timezone").text();
        // alert(ctz);
        $("#selectTimezone").val(ctz);

        $("#changeTimezone").on('click', function(e) {
            e.preventDefault();
            let token = $('[name=csrfmiddlewaretoken]').val();
            let ntz = $("#selectTimezone").val();
            console.log(ntz);
            $.ajax({
              headers: {'X-CSRFToken': token},
              type: 'POST',
              url: "{% url 'profile' %}",
              data: {"ntz": ntz},
              success: function(response) {
                console.log(response);
                location.reload();
              },
              error: function(response) {
                alert("error");
              }
            });
        });

        $("#changePassword").on('click', function(e) {
            e.preventDefault();
            let token = $('[name=csrfmiddlewaretoken]').val();
            let app_pass = $("#appPassword").val();
            console.log(app_pass);
            $.ajax({
              headers: {'X-CSRFToken': token},
              type: 'POST',
              url: "{% url 'profile' %}",
              data: {"app_pass": app_pass},
              success: function(response) {
                console.log(response);
                location.reload();
              },
              error: function(response) {
                alert("error");
              }
            });
        });
    })
</script>

{% endblock %}

ASR/templates/settings.html
{% extends 'header.html' %}
{% block title %}
  Settings
{% endblock %}

{% block content %}
	<p>Настройки</p>
{% endblock %}

ASR/templates/sign_in.html
{% extends 'header.html' %}
{% block title %}
  Sign In
{% endblock %}
{% block content %}
<div class="container mt-5">

    <div class="row justify-content-center">
        <div class="input-card">
            <!-- <img class="mb-4 justify-content-center" src="ASR_64x64.png" alt="" width="64" height="64"> -->
            <h1 class="text-center">Вход</h1>

            <div class="card-body">

                <div class="form-group">
                    <label for="exampleInputEmail1">Введите email</label>
                    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                    <!-- <small id="emailHelp" class="form-text text-muted">Логин может быть любым.</small> -->
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">Введите пароль</label>
                    <input type="password" class="form-control" id="exampleInputPassword1">
                </div>
                <a href="index.html" class="btn btn-primary">Войти</a>
                <a href="sign_up.html" class="btn btn-primary">Зарегистрироваться</a>

            </div>

        </div>
    </div>
</div>
{% endblock %}

ASR/templates/sign_up.html
{% extends 'header.html' %}
{% block title %}
  Sign Up
{% endblock %}
{%block content%}
<div class="container">
    <div class="row justify-content-center">
        <div class="input-card">
            <h1 class="text-center">Регистрация</h1>
                
                <div class="card-body">
                    <form>
                        <div class="form-group">
                            <label for="exampleInputEmail1">Введите Email</label>
                            <input type="email" class="form-control" id="exampleInputEmail1"
                                aria-describedby="emailHelp">
                        </div>
                        <div class="form-group">
                            <label for="exampleInputPassword1">Введите пароль</label>
                            <input type="password" class="form-control" id="exampleInputPassword1">
                        </div>
                        <div class="form-group">
                            <label for="exampleInputPassword1">Повторите пароль</label>
                            <input type="password" class="form-control" id="RepeatPassword1">
                        </div>
                        <a href="index.html" class="btn btn-primary">Зарегистрироваться</a>
                    </form>
                </div>
            
        </div>
    </div>
</div>
{% endblock %}